language: node_js
node_js: node
services: 
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: NrCMxGiMe39ITRDNz2NWpzX6JzHc3VSNSgV7cqrXMI87u2wc5mUXATiAf3yhTO1JGcYC8Mn1hG1H4/BVE5QTOcoeprR021DgBV1mGHx9J96fnMxN7Ja64P7H3t9IzCfJ4/FeCY1q+OWOJYFyxOLxSQWCluY4GvXT1OtRBCg278u3G9StEI9oo73cMLPm5qBn7NfZoZqBFZ70rVFeBdw6/IpOiq8kkHQ8tQV0e7GYHpJKyKUk3+dvU0VHylJoAbwWNWuDdpMiORYfZ9kfH7HHSpCbLMB6cvUls0HzLlC8Be+bqlJVFuwdoDns6Kth3T7QhIWlry0qB2c/OPFf+ijjbFCqAa1D+AOHqQZQQs0/c4skDcVeajkKxKvv1pDvKOQhdw2AddfuRugoePfJQi3jhL/ppIR2EYQkusDCaMuCATXZX1qojEtZh7DM8BQjgdm22rQVDh7gTOREzhclgPn/FtODBPxsLxcjK2sjn3IK39NIiYgb3+rlmCPoO/xWrIbd0YJB1eEE+AI5dyPuibFPLSS7KGYycvOd4KHa8EXXaLUhkW1hCf+RqQ9YhzqgZaFB9oxRr+UByDFutlaiqj8DpaSicn4o3q1WyvTw5aV1tUdFTbR8EA+lVqlqEF8NrSPBS5KSesz1qab8ZaJySTXcgd8Ie6sqzQvuzlKTEowN0xw=
  app: join-class
  on:
    repo: JasminTrotter/Join-Class-App
